# Generated by Django 4.2.6 on 2024-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menutype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('descd', models.TextField()),
                ('persons', models.IntegerField()),
                ('materialsgram', models.IntegerField()),
                ('materialsgram1', models.IntegerField()),
                ('materialsgram2', models.IntegerField()),
                ('materialsname', models.TextField()),
                ('materialsname1', models.TextField()),
                ('materialsname2', models.TextField()),
                ('time', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
