# Generated by Django 4.2.6 on 2024-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='category',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
