# Generated by Django 4.2.6 on 2024-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='special_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
